### ISSUE TITLE
How to correctly capitalize small words (a, an, the...) in the tittle.

### ISSUE THREAD

**Issue by yanghaoxie** [mrkkrp/fix-word#4]
According to this [web site](https://www.scribendi.com/advice/capitalization.en.html)

> All large words in the titles of movies, books, and other publications should be capitalized, while all small words (a, an, the, but, and, if, as, or, nor, to name a few) should not be capitalized unless they are the first or last words in the title:
A Life Less Ordinary (The word "A" would not normally be capitalized, but because it is the first word in the title, we must capitalize it.)
OR
War of the Worlds (The words "of" and "the" are not capitalized because they are small and are not at the beginning or end of the title, though exceptions to the "small words" rule do exist.)

So, how should we handle those scenarios when we capitalize words.

**Comment by akirak** [comment]
I don't understand why you care about this problem. `fix-word-capitalize` works on a word, and you can prevent capitalising those words by simply not running the command.

**Comment by yanghaoxie** [comment]
I will give an example to show my use case, I did not find a convenient way to achieve this.

Suppose I just write a title down, and I want to capitalize it.

I use `|` to denote the position of cursor.

> this is just a test and a stupid demo.|

Now after I execute `fix-word-capitalize` for 9 times.


> This Is Just A Test And A Stupid Demo.|

However, what I really want is, since small words should not be capitalized unless they are not at the beginning or end of the title

> This Is Just a Test and a Stupid Demo.|

**Comment by akirak** [comment]
Maybe what you really need is a custom version of `capitalize-region` command/function. It has nothing to do with this package, since it is a wrapper around built-in case conversion functions.

**Comment by yanghaoxie** [comment]
Thank you for you explanation!
